server:
  port: 8888

#监控信息完善：实例的说明信息
info:
  app:
    name: graduation-project-cluster-03
  company:
    name: www.yangyi.com
  build:
    artifactId: ${project.artifactId}
    version: ${project.artifactId}

# Actuator 健康监控配置
management:
  endpoints:
    web:
      exposure:
        include: "*"  # 定义暴露哪些端点，*为所有
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

# mybatis 配置
mybatis:
  # 指明 mybatis 配置文件所在路径
  config-location: classpath:mybatis/config/mybatis-config.xml
  # 指明 mybatis mapper文件所在路径
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

#Spring 相关配置
spring:
  application:
    # 服务名称，很重要，集群时要保持一致，这在以后的服务与服务之间相互调用一般都是根据这个name。
    name: graduation-project-cluster-03

  #BootAdmin配置
  boot:
    admin:
      client:
        url: "http://120.78.59.162:9999"  #指定 BootAdmin-Server 端的地址
        instance:
          #指定本服务的IP地址，让 BootAdmin 可以发现不同服务器上的应用
          service-url: "http://47.101.214.48:8888"
          #显示IP
          prefer-ip: true
  main:
      #遇到相同名字的bean可以被覆盖
      allow-bean-definition-overriding: true
  mvc:
      pathmatch:
        #正确处理Restful邮箱类型的数据传输问题
        use-registered-suffix-pattern: true

  #SpringSecurity配置
  security:
    user:
      name: admin
      password: toor
      roles: Role_Admin

  #数据源配置
  datasource:
    username: root
    password: toor
    url: jdbc:mysql://120.78.59.162:3308/graduation?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name:springBoot2.x 后驱动程序通过SPI自动注册，并且通常不需要手动加载驱动程序类。
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
     # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      # SpringBoot 2.x 此处记得去掉 log4j
      filters: stat,wall
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置监控服务器
      stat-view-servlet:
        login-username: admin
        login-password: toor
        reset-enable: false
        url-pattern: /druid/*
        # 添加IP白名单
        #allow:
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        #deny:
      web-stat-filter:
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式，一定要加上 ""，否则会报错
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

  # Redis，SpringBoot2.x默认使用 Lettuce 作为客户端
  redis:
    # 单体模式：Redis数据库索引（默认为0，有0~15，共16个库）
#    database: 0
#    # Redis服务器地址
#    host: 120.78.59.162
#    # Redis服务器连接端口
#    port: 6379

    # Redis服务器连接密码（默认为空）
    password: toor
   # 连接超时时间（毫秒）
    timeout: 10000

    #哨兵模式
    sentinel:
      #哨兵集群名称
      master: mymaster
      #哨兵节点
      nodes:
        - 120.78.59.162:26379
        - 47.101.189.171:26379
        - 47.101.214.48:26379

    #这里使用 Lettuce，Jedis的连接池在 SpringBoot2.x 已不推荐使用
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 50
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000 #毫秒
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
      #关闭超时时间，毫秒
      shutdown-timeout: 100

  #使用Spring Cache
  cache:
      type: redis
      redis:
        time-to-live: 600 #缓存持续时间 600 秒
      ehcache:
        config: ehcache.xml

